
# 运行环境， dev：开发环境，prod：生产环境
env: "dev"

server:
  http:
    port: 8080
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "admin123"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 100
redis:
  host: "localhost"
  port: "6379"
  db: 0
  password: ""
  pool_Size: 100