name: "web_app"
mode: "dev"
port: "8081"
version: "1.1.2"
start_time: "2020-09-14"
machine_id: 1

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "admin123"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 100
redis:
  host: "localhost"
  port: "6379"
  db: 0
  password: ""
  pool_Size: 100
